### ISSUE TITLE
IDictionary to plainobject

### ISSUE THREAD

**Issue by Psvensso** [CodySchrank/MTT#13]
We need to be able to express the JSON plain object in our C# interfaces. 

Either by `IDictionary<T1, T2>` or `KeyValuePair<T1, T2>`
Or actually any Map:isch type would do. Preferably Dictionary. 

Expected out: 
`{[key:T1]: T2}`

Example: 
`public KeyValuePair<string, string> Entities { get; set; }; ` >> `{[key:string]: string}`
`public IDictionary<string, IEntity[]> Entities { get; set; };` >> `{[key:string]: IEntity[]}`

**Comment by CodySchrank** [comment]
I agree I will look into this.

**Comment by CodySchrank** [comment]
I understand that this could be useful, but given Microsofts current recommendation of using `any` to represent JSON (https://github.com/Microsoft/TypeScript/issues/1897), I'm going to close this.
