### ISSUE TITLE
Dictionary not generated correctly

### ISSUE THREAD

**Issue by rcheung9** [CodySchrank/MTT#20]
I have a property like so
```
public UserSettingsVM Settings { get; set; }
public Dictionary<string, bool> Permissions { get; set; }
```
But it generates this
```
settings: UserSettingsVM;
bool>: any;
```

**Comment by JamesLoyd** [comment]
This problem also affects me as well.

```
public Dictionary<string, string> Partnerships { get; set; }
```

Gets generated to: 
```
string>: any;
```

**Comment by rcheung9** [comment]
@JamesLoyd The problem is the code splits lines by space.

Change to `Dictionary<string,string>` from `Dictionary<string, string>` and it will work.
