### ISSUE TITLE
Consider converting Dictionary to Map type.

### ISSUE THREAD

**Issue by CodySchrank** [CodySchrank/MTT#33]
`Map` is certainly more useful than `any` but I'm not sure of any potential downsides.

**Comment by Rudokus** [comment]
Feature wanted. Any status on this?

**Comment by CodySchrank** [comment]
Sure I'll add it to the next release.

**Comment by Rudokus** [comment]
When will this release be made? I could use it for a project I am working on.

**Comment by CodySchrank** [comment]
I'll add it in this weekend.
