### ISSUE TITLE
Collection properties marked virtual gets incorrectly translated.

### ISSUE THREAD

**Issue by elestedt** [CodySchrank/MTT#8]
```C#
public class Model {
  public virtual ICollection<OtherModel> OtherModels { get; set; }
}
```
gets turned into
```TypeScript
export interface Model {
    iCollection<OtherModel>: any;
}
```
Which is plainly wrong, remove the virtual keyword and it will work. It also works for properties that are not generic types.

The Virtual keyword is required for the [lazy-loading](https://docs.microsoft.com/en-us/ef/core/querying/related-data#lazy-loading) routines in EF Core 2.1 - but I don't see any reason for virtual properties to not be handled properly in this case.

**Comment by CodySchrank** [comment]
Certainly.  I don't use lazy loading in any of my projects so I kinda forgot about it!  I will merge if all is good and release a new version.

**Comment by elestedt** [comment]
Thanks for a quick merge :+1:
